using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

public static class GameDataCodeGenerator
{
    public const string OutputAssetPath = "Assets/Scripts/GameData/Generated/GameDataGenerated.cs";

    [MenuItem("Tools/Game Data/Regenerate Code")]
    public static void Regenerate()
    {
        GameDataSchemaRoot schema = GameDataIO.LoadSchema();
        if (schema == null)
        {
            Debug.LogError("GameDataCodeGenerator: failed to load schema.");
            return;
        }

        string code = Generate(schema);

        string dir = Path.GetDirectoryName(OutputAssetPath);
        if (!string.IsNullOrEmpty(dir))
        {
            Directory.CreateDirectory(dir);
        }

        File.WriteAllText(OutputAssetPath, code);
        AssetDatabase.ImportAsset(OutputAssetPath);

        int fieldCount = 0;
        for (int i = 0; i < schema.configTypes.Count; i++)
        {
            fieldCount += schema.configTypes[i].fields.Count;
        }

        Debug.Log(
            $"GameDataCodeGenerator: regenerated {schema.configTypes.Count} types ({fieldCount} fields) -> {OutputAssetPath}");
    }

    public static string Generate(GameDataSchemaRoot schema)
    {
        HashSet<string> typeNames = new(StringComparer.Ordinal);
        for (int i = 0; i < schema.configTypes.Count; i++)
        {
            string typeName = schema.configTypes[i].name;
            if (string.IsNullOrWhiteSpace(typeName))
            {
                Debug.LogWarning("GameDataCodeGenerator: skipping config type with empty name.");
                continue;
            }

            if (!IsValidIdentifier(typeName))
            {
                Debug.LogWarning(
                    $"GameDataCodeGenerator: config type name '{typeName}' is not a valid C# identifier. Generated code will not compile.");
            }

            typeNames.Add(typeName);
        }

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// This file was produced by GameDataCodeGenerator.");
        sb.AppendLine("// Do not edit by hand. Regenerate via Tools > Game Data > Regenerate Code.");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using GameData.Converters;");
        sb.AppendLine("using Newtonsoft.Json;");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();
        sb.AppendLine("namespace GameData");
        sb.AppendLine("{");

        for (int i = 0; i < schema.configTypes.Count; i++)
        {
            GameDataConfigTypeDef type = schema.configTypes[i];
            if (string.IsNullOrWhiteSpace(type.name))
            {
                continue;
            }

            AppendClass(sb, type, typeNames);
            sb.AppendLine();
        }

        AppendTypeMap(sb, schema);

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static void AppendClass(StringBuilder sb, GameDataConfigTypeDef type, HashSet<string> validTypeNames)
    {
        string className = type.name + "Data";
        sb.AppendLine($"    public sealed class {className} : DataEntity");
        sb.AppendLine("    {");

        for (int f = 0; f < type.fields.Count; f++)
        {
            GameDataFieldDef field = type.fields[f];
            if (string.IsNullOrWhiteSpace(field.name))
            {
                continue;
            }

            if (!IsValidIdentifier(field.name))
            {
                Debug.LogWarning(
                    $"GameDataCodeGenerator: field name '{type.name}.{field.name}' is not a valid C# identifier. Generated code will not compile.");
            }

            AppendField(sb, field, validTypeNames);
        }

        sb.AppendLine("    }");
    }

    private static void AppendField(StringBuilder sb, GameDataFieldDef field, HashSet<string> validTypeNames)
    {
        string propertyName = ToPascalCase(field.name);
        string camelProp = ToCamelCase(propertyName);

        switch (field.type)
        {
            case GameDataFieldType.Int:
                sb.AppendLine(
                    $"        [JsonProperty(\"{field.name}\")] public int {propertyName} {{ get; private set; }}");
                break;

            case GameDataFieldType.Float:
                sb.AppendLine(
                    $"        [JsonProperty(\"{field.name}\")] public float {propertyName} {{ get; private set; }}");
                break;

            case GameDataFieldType.Bool:
                sb.AppendLine(
                    $"        [JsonProperty(\"{field.name}\")] public bool {propertyName} {{ get; private set; }}");
                break;

            case GameDataFieldType.String:
                sb.AppendLine(
                    $"        [JsonProperty(\"{field.name}\")] public string {propertyName} {{ get; private set; }} = string.Empty;");
                break;

            case GameDataFieldType.Vector2:
                sb.AppendLine(
                    $"        [JsonProperty(\"{field.name}\"), JsonConverter(typeof(Vector2JsonConverter))] public Vector2 {propertyName} {{ get; private set; }}");
                break;

            case GameDataFieldType.Vector3:
                sb.AppendLine(
                    $"        [JsonProperty(\"{field.name}\"), JsonConverter(typeof(Vector3JsonConverter))] public Vector3 {propertyName} {{ get; private set; }}");
                break;

            case GameDataFieldType.Color:
                sb.AppendLine(
                    $"        [JsonProperty(\"{field.name}\"), JsonConverter(typeof(ColorJsonConverter))] public Color {propertyName} {{ get; private set; }}");
                break;

            case GameDataFieldType.Sprite:
                AppendAssetField(sb, field.name, propertyName, camelProp, "Sprite");
                break;

            case GameDataFieldType.Mesh:
                AppendAssetField(sb, field.name, propertyName, camelProp, "Mesh");
                break;

            case GameDataFieldType.Prefab:
                AppendAssetField(sb, field.name, propertyName, camelProp, "GameObject");
                break;

            case GameDataFieldType.Ref:
                AppendRefField(sb, field, propertyName, camelProp, validTypeNames);
                break;

            default:
                sb.AppendLine($"        // Unsupported field type for '{field.name}': {field.type}");
                break;
        }
    }

    private static void AppendAssetField(
        StringBuilder sb,
        string jsonName,
        string propertyName,
        string camelProp,
        string assetType)
    {
        string pathField = $"_{camelProp}Path";
        string assetField = $"_{camelProp}";
        string loadedField = $"_{camelProp}Loaded";

        sb.AppendLine(
            $"        [JsonProperty(\"{jsonName}\")] private string {pathField} = string.Empty;");
        sb.AppendLine($"        [JsonIgnore] private {assetType} {assetField};");
        sb.AppendLine($"        [JsonIgnore] private bool {loadedField};");
        sb.AppendLine($"        [JsonIgnore] public {assetType} {propertyName}");
        sb.AppendLine("        {");
        sb.AppendLine("            get");
        sb.AppendLine("            {");
        sb.AppendLine($"                if (!{loadedField})");
        sb.AppendLine("                {");
        sb.AppendLine(
            $"                    {assetField} = string.IsNullOrEmpty({pathField}) ? null : Resources.Load<{assetType}>({pathField});");
        sb.AppendLine($"                    {loadedField} = true;");
        sb.AppendLine("                }");
        sb.AppendLine($"                return {assetField};");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    private static void AppendRefField(
        StringBuilder sb,
        GameDataFieldDef field,
        string propertyName,
        string camelProp,
        HashSet<string> validTypeNames)
    {
        if (string.IsNullOrWhiteSpace(field.refType) || !validTypeNames.Contains(field.refType))
        {
            Debug.LogWarning(
                $"GameDataCodeGenerator: Ref field '{field.name}' has invalid refType '{field.refType}'. Emitting raw string accessor.");
            sb.AppendLine(
                $"        [JsonProperty(\"{field.name}\")] public string {propertyName}Id {{ get; private set; }} = string.Empty;");
            return;
        }

        string targetClass = field.refType + "Data";
        string idField = $"_{camelProp}Id";
        string entityField = $"_{camelProp}";
        string resolvedField = $"_{camelProp}Resolved";

        sb.AppendLine($"        [JsonProperty(\"{field.name}\")] private string {idField} = string.Empty;");
        sb.AppendLine($"        [JsonIgnore] private {targetClass} {entityField};");
        sb.AppendLine($"        [JsonIgnore] private bool {resolvedField};");
        sb.AppendLine($"        [JsonIgnore] public {targetClass} {propertyName}");
        sb.AppendLine("        {");
        sb.AppendLine("            get");
        sb.AppendLine("            {");
        sb.AppendLine($"                if (!{resolvedField})");
        sb.AppendLine("                {");
        sb.AppendLine(
            $"                    {entityField} = string.IsNullOrEmpty({idField}) ? null : GameDataRegistry.Get<{targetClass}>({idField});");
        sb.AppendLine($"                    {resolvedField} = true;");
        sb.AppendLine("                }");
        sb.AppendLine($"                return {entityField};");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
    }

    private static void AppendTypeMap(StringBuilder sb, GameDataSchemaRoot schema)
    {
        sb.AppendLine("    public static class GameDataTypes");
        sb.AppendLine("    {");
        sb.AppendLine(
            "        public static readonly IReadOnlyDictionary<string, Type> Map = new Dictionary<string, Type>(StringComparer.Ordinal)");
        sb.AppendLine("        {");

        for (int i = 0; i < schema.configTypes.Count; i++)
        {
            string typeName = schema.configTypes[i].name;
            if (string.IsNullOrWhiteSpace(typeName))
            {
                continue;
            }

            sb.AppendLine($"            {{ \"{typeName}\", typeof({typeName}Data) }},");
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    private static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }

        return char.ToUpperInvariant(name[0]) + (name.Length > 1 ? name.Substring(1) : string.Empty);
    }

    private static string ToCamelCase(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return name;
        }

        return char.ToLowerInvariant(name[0]) + (name.Length > 1 ? name.Substring(1) : string.Empty);
    }

    private static bool IsValidIdentifier(string name)
    {
        if (string.IsNullOrEmpty(name))
        {
            return false;
        }

        if (!char.IsLetter(name[0]) && name[0] != '_')
        {
            return false;
        }

        for (int i = 1; i < name.Length; i++)
        {
            if (!char.IsLetterOrDigit(name[i]) && name[i] != '_')
            {
                return false;
            }
        }

        return true;
    }
}
